// @ts-nocheck
import Prism from 'prismjs'

// Languages
import 'prismjs/components/prism-javascript'
import 'prismjs/components/prism-typescript'
import 'prismjs/components/prism-jsx'
import 'prismjs/components/prism-json'
import 'prismjs/components/prism-markup'
import 'prismjs/components/prism-markdown'
import 'prismjs/components/prism-bash'
import 'prismjs/components/prism-css'
import 'prismjs/components/prism-scss'
import 'prismjs/components/prism-sass'
import 'prismjs/components/prism-less'
import 'prismjs/components/prism-tsx'
import 'prismjs/components/prism-python'
import 'prismjs/components/prism-c'
import 'prismjs/components/prism-cpp'
import 'prismjs/components/prism-csharp'
import 'prismjs/components/prism-go'
import 'prismjs/components/prism-ruby'
import 'prismjs/components/prism-rust'
import 'prismjs/components/prism-csv'
import 'prismjs/components/prism-docker'
import 'prismjs/components/prism-nginx'
import 'prismjs/components/prism-mongodb'
import 'prismjs/components/prism-makefile'
import 'prismjs/components/prism-lua'
import 'prismjs/components/prism-latex'
import 'prismjs/components/prism-ignore'
import 'prismjs/components/prism-graphql'
import 'prismjs/components/prism-powershell'
import 'prismjs/components/prism-jsx'
import 'prismjs/components/prism-tsx'
import 'prismjs/components/prism-regex'
import 'prismjs/components/prism-sql'
import 'prismjs/components/prism-toml'
import 'prismjs/components/prism-vim'
import 'prismjs/components/prism-visual-basic'
import 'prismjs/components/prism-yaml'

// Plugins
// import 'prismjs/plugins/autoloader/prism-autoloader.min.js'
// import 'prismjs/plugins/line-numbers/prism-line-numbers.min.js'
// import 'prismjs/plugins/line-numbers/prism-line-numbers.min.css'
// import 'prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.min.js'
import 'prismjs/plugins/toolbar/prism-toolbar.min.js'
import 'prismjs/plugins/toolbar/prism-toolbar.css'
// import 'prismjs/plugins/show-language/prism-show-language.min.js'
import 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js'
// import 'prismjs/plugins/autolinker/prism-autolinker.min.js'
// import 'prismjs/plugins/autolinker/prism-autolinker.css'
// import 'prismjs/plugins/data-uri-highlight/prism-data-uri-highlight.min.js'
// import 'prismjs/plugins/diff-highlight/prism-diff-highlight.min.js'
// import 'prismjs/plugins/diff-highlight/prism-diff-highlight.css'
// import 'prismjs/plugins/file-highlight/prism-file-highlight.min.js'
// import 'prismjs/plugins/filter-highlight-all/prism-filter-highlight-all.min.js'
// import 'prismjs/plugins/highlight-keywords/prism-highlight-keywords.min.js'
// import 'prismjs/plugins/inline-color/prism-inline-color.min.js'
// import 'prismjs/plugins/inline-color/prism-inline-color.min.css'
// import 'prismjs/plugins/jsonp-highlight/prism-jsonp-highlight.min.js'
// import 'prismjs/plugins/keep-markup/prism-keep-markup.min.js'
// import 'prismjs/plugins/command-line/prism-command-line.min.js'
// import 'prismjs/plugins/command-line/prism-command-line.css'
// import 'prismjs/plugins/custom-class/prism-custom-class.min.js'
// import 'prismjs/plugins/download-button/prism-download-button.min.js'
// import 'prismjs/plugins/line-highlight/prism-line-highlight.min.js'
// import 'prismjs/plugins/line-highlight/prism-line-highlight.min.css'
// import 'prismjs/plugins/match-braces/prism-match-braces.min.js'
// import 'prismjs/plugins/match-braces/prism-match-braces.min.css'
// import 'prismjs/plugins/previewers/prism-previewers.min.js'
// import 'prismjs/plugins/previewers/prism-previewers.min.css'
// import 'prismjs/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js'
// import 'prismjs/plugins/treeview/prism-treeview.min.js'
// import 'prismjs/plugins/treeview/prism-treeview.min.css'
// import 'prismjs/plugins/unescaped-markup/prism-unescaped-markup.min.js'
// import 'prismjs/plugins/unescaped-markup/prism-unescaped-markup.min.css'
// import 'prismjs/plugins/show-invisibles/prism-show-invisibles.min.js'
// import 'prismjs/plugins/show-invisibles/prism-show-invisibles.min.css'
// import 'prismjs/plugins/wpd/prism-wpd.min.js'
// import 'prismjs/plugins/wpd/prism-wpd.min.css'

// Theme
import 'prismjs/themes/prism-tomorrow.css'
// import 'prismjs/themes/prism-coy.css'
// import 'prismjs/themes/prism-okaidia.css'
// import 'prismjs/themes/prism-solarizedlight.css'

typeof window !== 'undefined' && (window.Prism = Prism) // Assign Prism to the window object

export default Prism
