const Educations = [
    {
        id: 1,
        slug: "Shanghai Jiao Tong University",
        school: "Shanghai Jiao Tong University",
        image: '/images/educations/SHJU.svg',
        degree: "B.S.C",
        address: "China, Shang Hai Shi, Min Hang Qu",
        field_of_study: "Computer Science",
        duration: "Feb 2011 ~ Jul 2016",
        grade: "First Class (1st)/ 86% Marks / CGPA 4.52 out of 5.00",
        // activities?: string,
        // description?: string,
        // education_media?: MediaType[],
        created_at: "May 07 2021",
        updated_at: "May 07 2021",
    },
    {
        id: 2,
        slug: "Shanghai High School",
        school: "Shanghai High School",
        image: '/images/educations/SHS.svg',
        degree: "Top mark",
        address: "Baise Road, Shanghai, China",
        field_of_study: "Science",
        duration: "SEP 2008 ~ Nov 2010",
        grade: "First Class (1st)/ 92% Marks / CGPA 5.00 out of 5.00",
        created_at: "May 07 2021",
        updated_at: "May 07 2021",
    },
    {
        id: 3,
        slug: "Shanghai Gold Apple School",
        school: "Shanghai Gold Apple School",
        image: '/images/educations/SGAS1.png',
        degree: "Top mark",
        address: "Pu Dong Xin Qu, Shang Hai Shi, China",
        field_of_study: "Science",
        duration: "APR 2005 ~ SEP 2008",
        grade: "GPA 5.00 out of 5.00",
        created_at: "May 07 2021",
        updated_at: "May 07 2021",
    },
];

export default Educations;