const Experience = [
    {
        id: 1,
        slug: "111",
        company: "Ruby Exchange",
        company_image: "/images/companies/rubyexchange.svg",
        company_url: "https://ruby.exchange/",
        address: "Flughafen, Zürich, Switzerland",
        designation: "Senior Blockchain Developer",
        job_type: "Full Time",
        job_location_type: "Hybrid",
        start_date: "Nov 2021",
        end_date: "Feb 2023",
        duration: "Nov 2021 - Feb 2023",
        duration_in_days: "(1 year, 3 months)",
        currently_working: "string",
        description: `<div class="relative md:border-gray-300 md:dark:border-gray-400 md:col-span-4 text-sm text-inherit font-light pt-6"><p class="MsoListParagraphCxSpFirst" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]-->&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora; font-weight: bold; font-size: 16px; margin-bottom: 5px">DEX platform for crypto trading on Ethergem blockchain.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Developed a web UI of DEX platform for crypto trading using Next.JS.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Created Backend with Solidity and Subgraph.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Used Redux as state management, TailwindCSS and MUI for UI styling.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Tested the UI using Jest framework.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Interacted with blockchain using ethers module.</span></p></div>`,
        created_at: "string",
        updated_at: "string",
    },
    // {
    //     id: 2,
    //     slug: "string",
    //     company: "string",
    //     company_image: "string",
    //     company_url: "string",
    //     address: "string",
    //     designation: "string",
    //     job_type: "string",
    //     job_location_type: "string",
    //     start_date: "string",
    //     end_date: "string",
    //     duration: "string",
    //     duration_in_days: "string",
    //     currently_working: "string",
    //     description: "string",
    //     created_at: "string",
    //     updated_at: "string",
    // },
    // {
    //     id: 3,
    //     slug: "string",
    //     company: "string",
    //     company_image: "string",
    //     company_url: "string",
    //     address: "string",
    //     designation: "string",
    //     job_type: "string",
    //     job_location_type: "string",
    //     start_date: "string",
    //     end_date: "string",
    //     duration: "string",
    //     duration_in_days: "string",
    //     currently_working: "string",
    //     description: "string",
    //     created_at: "string",
    //     updated_at: "string",
    // },
    // {
    //     id: 4,
    //     slug: "string",
    //     company: "string",
    //     company_image: "string",
    //     company_url: "string",
    //     address: "string",
    //     designation: "string",
    //     job_type: "string",
    //     job_location_type: "string",
    //     start_date: "string",
    //     end_date: "string",
    //     duration: "string",
    //     duration_in_days: "string",
    //     currently_working: "string",
    //     description: "string",
    //     created_at: "string",
    //     updated_at: "string",
    // }
];

export default Experience;