const MyProfile = {
    id: 1,
    username: "daveescott",
    email: "daveescott0509@gmail.com",
    name: "Davee Scott",
    slug: "daveescott",
    nickname: "OnlyForward",
    gender: "M",
    image: '/images/davee.jpg',
    dob: "string",
    website: "string",
    contact: "string",
    contact_email: "daveescott0509@gmail.com",
    linkedin: "https://www.linkedin.com/in/davee-scott",
    github: "https://github.com/OnlyForward0613",
    address: "12900 East Shelby Lane",
    about: "string",
    is_portfolio_user: "string",
    resume_link: "https://drive.google.com/file/d/1gE0HAqNyah08KKyNlPji0PeAusMRFe4Y/view?usp=sharing",
    is_active: "string",
    is_staff: "string",
    is_superuser: "string",
    date_joined: "6 Jul 2024",
    last_login: "6 Jul 2024",
    updated_at: "6 Jul 2024",
};

export default MyProfile;