const Skills = [
    {
        id: 1,
        slug: "Solidity",
        title: "Solidity",
        image: "/images/skills/solidity.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 2,
        slug: "Rust",
        title: "Rust",
        image: "/images/skills/rust.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 3,
        slug: "Ethereum",
        title: "Ethereum",
        image: "/images/skills/Ethereum.png",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 4,
        slug: "Solana",
        title: "Solana",
        image: "/images/skills/solana.png",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 5,
        slug: "Foundry",
        title: "Foundry",
        image: "/images/skills/foundry.png",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 6,
        slug: "Anchor",
        title: "Anchor",
        image: "/images/skills/anchor.png",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 7,
        slug: "React",
        title: "React",
        image: "/images/skills/React.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 8,
        slug: "Next",
        title: "Next",
        image: "/images/skills/Next.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 9,
        slug: "TailWindCss",
        title: "TailWindCss",
        image: "/images/skills/Tailwindcss.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 10,
        slug: "MobileApp",
        title: "MobileApp",
        image: "/images/skills/Android.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
];

export default Skills;