# Generated by Django 4.0.10 on 2023-08-26 00:27

from django.db import migrations, models
import django.db.models.deletion
import utils.image_upload_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('overview', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.image_upload_helpers.get_code_snippet_image_path)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Published', max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code Snippet',
                'verbose_name_plural': 'Code Snippets',
                'db_table': 'code_snippet',
                'ordering': ('-order', '-created_at'),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='CodeSnippetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('comment', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='code_snippets.codesnippet')),
            ],
            options={
                'verbose_name': 'Code Snippet Comment',
                'verbose_name_plural': 'Code Snippet Comments',
                'db_table': 'code_snippet_comment',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='CodeSnippetView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('first_visited_at', models.DateTimeField(auto_now_add=True)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('liked', models.BooleanField(default=False)),
                ('code_snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='code_snippets.codesnippet')),
            ],
            options={
                'verbose_name': 'Code Snippet View',
                'verbose_name_plural': 'Code Snippet Views',
                'db_table': 'code_snippet_view',
                'ordering': ('-last_visited_at',),
                'get_latest_by': 'created_at',
                'unique_together': {('clientID', 'code_snippet')},
            },
        ),
    ]
