# Generated by Django 4.0.10 on 2023-07-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_professionalexperience_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
