# Generated by Django 4.0.10 on 2023-07-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_interest_order_alter_project_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
