# Generated by Django 4.0.10 on 2023-07-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_alter_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='job_location_type',
            field=models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contractual', 'Contractual')], default='Full Time', max_length=20),
        ),
    ]
